### PR TITLE
Convert to TypeScript

### PR DESCRIPTION
**Pull request by tmoleary21**
I converted the project to use VITE and all the starter files to use TypeScript. I did this by starting a new VITE project and copying over the files, then adding types. It is pretty much the same as it was, with little changes outside typing

### CODE REVIEW

**Review by honeybadgerofdoom — CHANGES_REQUESTED** [review]
Thanks so much for doing this! Just a couple of thoughts.

1) I'm getting this error after running `npm run dev`
---------------------------------------------------------------------------------------
(base) matthewyoung@MacBook-Pro-279 intro_to_react % npm run dev

> onboarding-project@0.0.0 dev
> vite


  VITE v5.0.2  ready in 798 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "@emotion/react"

    node_modules/@emotion/styled/dist/emotion-styled.browser.esm.js:5:7:
      5 │ import '@emotion/react';
        ╵        ~~~~~~~~~~~~~~~~

  You can mark the path "@emotion/react" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@emotion/react"

    node_modules/@emotion/styled/base/dist/emotion-styled-base.browser.esm.js:4:47:
      4 │ import { withEmotionCache, ThemeContext } from '@emotion/react';
        ╵                                                ~~~~~~~~~~~~~~~~

  You can mark the path "@emotion/react" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.
---------------------------------------------------------------------------------------

Did you ever see this on your end?

2) We should put the node version requirement for `vite` in the `README.md` file.

**Comment by tmoleary21** [comment]
@honeybadgerofdoom
1. I don't have that problem. I tried deleting node_modules and package-lock.json and reinstalling, and it all worked fine. Have you run `npm install` again?
2. I will add the requirement now. Good idea!

**Comment by tmoleary21** [comment]
I gave that a try but still didn't get the error. Maybe we could take a look together tomorrow or Wednesday in the meeting? @honeybadgerofdoom

**Comment by honeybadgerofdoom** [comment]
@tmoleary21 that sounds good. Maybe I'm just missing something obvious. Otherwise this looks great to me!

**Pull request merged**
